### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by 111678900** [jdonnelly36/AsymMirai#1]
Hello, My code throws the following error:：
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Input In [1], in <cell line: 7>()
      5 torch.cuda.set_device(0)
      6 torch.manual_seed(0)
----> 7 main(device_ids=[0],
      8         batch_size=30,
      9         lr=0.005,
     10         use_addon_layers=False,
     11         use_stretch_matrix=True,
     12         initial_asym_mean=2000,#*20,
     13         initial_asym_std=300,
     14         flexible_asymmetry=True,
     15         max_workers=8,
     16         align_images=False,
     17         latent_h=5,
     18         latent_w=5,
     19         save_file_suffix="./training_preds/full_model_epoch_0_full.pt",
     20         use_all_training_data=False,
     21         oversample_cancer_rate=None,
     22         topk_for_heatmap=None,
     23         multiple_pairs_per_exam=False)

File ~/autodl-tmp/AsymMirai/asymmetry_model/train.py:127, in main(device_ids, num_epochs, use_stretch, train_backbone, flexible_asymmetry, use_stretch_matrix, batch_size, lr, max_workers, initial_asym_mean, initial_asym_std, latent_h, latent_w, use_addon_layers, save_file_suffix, use_all_training_data, oversample_cancer_rate, topk_for_heatmap, align_images, multiple_pairs_per_exam, verbose, model, batch_acc, use_bias, lr_step_size, weight_decay, use_bn, linear_only_epochs)
    125 if model == None:
    126     print("Loading model from scratch")
--> 127     model = LocalizedDifModel(asymmetry_metric=hybrid_asymmetry,
    128                 embedding_channel=512,
    129                 latent_h=latent_h,
    130                 latent_w=latent_w,
    131                 embedding_model=None,
    132                 initial_asym_mean=initial_asym_mean,
    133                 initial_asym_std=initial_asym_std,
    134                 use_stretch=use_stretch,
    135                 train_backbone=train_backbone,
    136                 flexible_asymmetry=flexible_asymmetry,
    137                 use_stretch_matrix=use_stretch_matrix,
    138                 device_ids=device_ids,
    139                 use_addon_layers=use_addon_layers,
    140                 topk_for_heatmap=topk_for_heatmap,
    141                 use_bias=use_bias,
    142                 use_bn=use_bn)
    144 if oversample_cancer_rate is not None:
    145     loss_func = torch.nn.CrossEntropyLoss()

File ~/autodl-tmp/AsymMirai/asymmetry_model/mirai_localized_dif_head.py:76, in LocalizedDifModel.__init__(self, alignment_space, asymmetry_metric, latent_h, latent_w, embedding_channel, embedding_model, use_stretch, train_backbone, initial_asym_mean, initial_asym_std, flexible_asymmetry, use_stretch_matrix, device_ids, use_addon_layers, topk_for_heatmap, use_bias, use_bn)
     74 # Getting the embedding layers from Mirai
     75 if embedding_model is None:
---> 76     mirai = extract_mirai_backbone('../snapshots/mgh_mammo_MIRAI_Base_May20_2019.p')
     77     mirai.requires_grad = train_backbone
     78     if use_addon_layers:

File ~/autodl-tmp/AsymMirai/asymmetry_model/mirai_localized_dif_head.py:9, in extract_mirai_backbone(path)
      6 def extract_mirai_backbone(path):
      7 
      8     # first pull mirai onto the CPU to avoid putting the whole transformer on the gpu
----> 9     mirai = torch.load(path, map_location='cpu')
     10     embedding = []
     11     for l in mirai.children():

File ~/miniconda3/lib/python3.8/site-packages/torch/serialization.py:699, in load(f, map_location, pickle_module, **pickle_load_args)
    696 if 'encoding' not in pickle_load_args.keys():
    697     pickle_load_args['encoding'] = 'utf-8'
--> 699 with _open_file_like(f, 'rb') as opened_file:
    700     if _is_zipfile(opened_file):
    701         # The zipfile reader is going to advance the current file position.
    702         # If we want to actually tail call to torch.jit.load, we need to
    703         # reset back to the original position.
    704         orig_position = opened_file.tell()

File ~/miniconda3/lib/python3.8/site-packages/torch/serialization.py:231, in _open_file_like(name_or_buffer, mode)
    229 def _open_file_like(name_or_buffer, mode):
    230     if _is_path(name_or_buffer):
--> 231         return _open_file(name_or_buffer, mode)
    232     else:
    233         if 'w' in mode:

File ~/miniconda3/lib/python3.8/site-packages/torch/serialization.py:212, in _open_file.__init__(self, name, mode)
    211 def __init__(self, name, mode):
--> 212     super(_open_file, self).__init__(open(name, mode))

FileNotFoundError: [Errno 2] No such file or directory: '../snapshots/mgh_mammo_MIRAI_Base_May20_2019.p'

**Comment by 111678900** [comment]
can you tell me how to deal with it?

**Comment by jdonnelly36** [comment]
Thank you for raising this issue! In order to train AsymMirai, you will need to download the publicly trained weights from Mirai's backbone and place them in a directory named snapshots in the root directory for this repository. These weights are now available here: [https://duke.box.com/s/g21ak9kfneudotokp9nmlp07r1bsdki7](https://duke.box.com/s/g21ak9kfneudotokp9nmlp07r1bsdki7). The readme has been updated to reflect this.
